/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Confirm
         * @description Commit a board or roll batch against the current draw, in one transaction.
         */
        post: operations["post_confirm_api_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/draw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Draw
         * @description Build today's draw. Idempotent on the `draw_day` marker.
         *
         *     The only route in the drill loop that reads the calendar.
         */
        post: operations["post_draw_api_draw_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/draw/boards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Boards
         * @description The next `n` boards of the current draw.
         */
        get: operations["read_boards_api_draw_boards_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/draw/roll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Roll
         * @description `n` due roll pairs of the current draw.
         */
        get: operations["read_roll_api_draw_roll_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/grade": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Grade
         * @description Grade a board's typed answers. The only Claude call; writes nothing.
         */
        post: operations["post_grade_api_grade_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Groups
         * @description Every group with its description, note count and live pair count.
         */
        get: operations["read_groups_api_groups_get"];
        put?: never;
        /**
         * Post Group
         * @description Create a group from a name and description the user approved.
         */
        post: operations["post_group_api_groups_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/{group_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Group
         * @description One group's notes and pairs.
         */
        get: operations["read_group_api_groups__group_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Group
         * @description Reword a name or description.
         */
        patch: operations["patch_group_api_groups__group_id__patch"];
        trace?: never;
    };
    "/api/home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Home
         * @description The three backlog counts and today's draw status.
         */
        get: operations["read_home_api_home_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/misses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Misses
         * @description The drill record, newest first.
         */
        get: operations["read_misses_api_misses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Notes
         * @description Notes by any combination of the filters.
         */
        get: operations["read_notes_api_notes_get"];
        put?: never;
        /**
         * Post Note
         * @description Create a note against a source.
         */
        post: operations["post_note_api_notes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notes/{note_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Note
         * @description Delete a note. Refused once the note has a placement.
         */
        delete: operations["delete_note_api_notes__note_id__delete"];
        options?: never;
        head?: never;
        /**
         * Patch Note
         * @description Edit a statement. Refused once the note has a placement.
         */
        patch: operations["patch_note_api_notes__note_id__patch"];
        trace?: never;
    };
    "/api/placements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Placements
         * @description The wordsmithing queue.
         */
        get: operations["read_placements_api_placements_get"];
        put?: never;
        /**
         * Post Placements
         * @description Batch place notes.
         */
        post: operations["post_placements_api_placements_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/placements/{placement_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Placement
         * @description Move a placement. Sets `pairs_stale`; deletes a group the move empties.
         */
        patch: operations["patch_placement_api_placements__placement_id__patch"];
        trace?: never;
    };
    "/api/placements/{placement_id}/pairs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Put Pairs
         * @description Write the pair set whole; clears `pairs_stale`.
         */
        put: operations["put_pairs_api_placements__placement_id__pairs_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Sources
         * @description Search author, year and publication.
         */
        get: operations["read_sources_api_sources_get"];
        put?: never;
        /**
         * Post Source
         * @description Create a source.
         */
        post: operations["post_source_api_sources_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Answer
         * @description What was typed into one due pair's two boxes.
         */
        Answer: {
            /** Recall Pair Id */
            recall_pair_id: number;
            /** User Answer */
            user_answer: string;
            /** User Source */
            user_source: string;
        };
        /**
         * Board
         * @description One group's pairs, worked as a unit.
         */
        Board: {
            /** Context */
            context: components["schemas"]["ContextPair"][];
            /** Due */
            due: components["schemas"]["DuePair"][];
            /** Group Id */
            group_id: number;
            /** Group Name */
            group_name: string;
            /** Pair Count */
            pair_count: number;
        };
        /**
         * ConfirmRequest
         * @description A whole board's outcomes, committed in one transaction.
         */
        ConfirmRequest: {
            /** Results */
            results: components["schemas"]["ConfirmResult"][];
        };
        /**
         * ConfirmResult
         * @description One pair's outcome, after any contest the user made.
         */
        ConfirmResult: {
            /** Correct */
            correct: boolean;
            /** Recall Pair Id */
            recall_pair_id: number;
            /** User Answer */
            user_answer: string;
            /** User Source */
            user_source: string;
        };
        /**
         * ContextPair
         * @description A pair shown answered alongside the due ones.
         */
        ContextPair: {
            /** Answer */
            answer: string;
            /** Id */
            id: number;
            /** Question */
            question: string;
            source: components["schemas"]["Source"];
        };
        /**
         * DrawSummary
         * @description The current draw, as numbers.
         *
         *     `day` may be earlier than today: the current draw is the one most recently
         *     built and stays current until the next one replaces it — see
         *     design/Data.md#the-draw. `drawn` is how many came out and `expected` is how
         *     many were expected to, frozen at build time — neither falls; the other three
         *     do, as the morning is worked.
         */
        DrawSummary: {
            /** Boards */
            boards: number;
            /** Day */
            day: string;
            /** Drawn */
            drawn: number;
            /** Due */
            due: number;
            /** Expected */
            expected: number;
            /** Roll */
            roll: number;
        };
        /**
         * DuePair
         * @description A pair to be answered. Its answer is deliberately not sent.
         */
        DuePair: {
            /** Id */
            id: number;
            /** Question */
            question: string;
        };
        /**
         * GradeRequest
         * @description A board's typed answers. Grading writes nothing.
         */
        GradeRequest: {
            /** Answers */
            answers: components["schemas"]["Answer"][];
        };
        /**
         * GradeResponse
         * @description One verdict per answer submitted.
         */
        GradeResponse: {
            /** Verdicts */
            verdicts: components["schemas"]["Verdict"][];
        };
        /**
         * Group
         * @description A group, with the two counts that say how big it has grown.
         */
        Group: {
            /** Description */
            description: string;
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Note Count */
            note_count: number;
            /** Pair Count */
            pair_count: number;
        };
        /**
         * GroupCreate
         * @description A group the user named and whose description the user approved.
         */
        GroupCreate: {
            /** Description */
            description: string;
            /** Name */
            name: string;
        };
        /**
         * GroupDetail
         * @description One group's notes and pairs.
         */
        GroupDetail: {
            group: components["schemas"]["Group"];
            /** Notes */
            notes: components["schemas"]["Note"][];
            /** Pairs */
            pairs: components["schemas"]["Pair"][];
        };
        /**
         * GroupEdit
         * @description A reworded name or description. Omitted fields are left alone.
         */
        GroupEdit: {
            /** Description */
            description?: string | null;
            /** Name */
            name?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Home
         * @description The three backlog counts, the live corpus, and the current draw.
         *
         *     `pairs` is every live pair and is always present. `expected` is the live sum
         *     over them — what a build right now would come out at — and is set **only**
         *     when no draw has ever been built; once there is a marker the number that
         *     matters is `draw.expected`, frozen at that draw's build. See
         *     design/api/API.md#the-drill-loop.
         */
        Home: {
            draw?: components["schemas"]["DrawSummary"] | null;
            /** Expected */
            expected?: number | null;
            /** Pairs */
            pairs: number;
            /** Placements Stale */
            placements_stale: number;
            /** Placements Without Pairs */
            placements_without_pairs: number;
            /** Ungrouped Notes */
            ungrouped_notes: number;
        };
        /**
         * Miss
         * @description One missed drill, with what it was a miss of.
         */
        Miss: {
            /** Answer */
            answer: string;
            /** Day */
            day: string;
            /** Group Id */
            group_id: number | null;
            /** Group Name */
            group_name: string | null;
            /** Id */
            id: number;
            /** Question */
            question: string;
            /** Recall Pair Id */
            recall_pair_id: number;
            /** User Answer */
            user_answer: string;
            /** User Source */
            user_source: string;
        };
        /**
         * Note
         * @description A note, with the source it came from.
         *
         *     `placed` is what makes the edit and delete controls disappear on the entry
         *     screen — see design/app/Entry.md#entered-today.
         */
        Note: {
            /** Created On */
            created_on: string;
            /** Id */
            id: number;
            /** Placed */
            placed: boolean;
            source: components["schemas"]["Source"];
            /** Statement */
            statement: string;
        };
        /**
         * NoteCreate
         * @description What saving a note asks for.
         */
        NoteCreate: {
            /** Source Id */
            source_id: number;
            /** Statement */
            statement: string;
        };
        /**
         * NoteEdit
         * @description A correction to a note that has no placement.
         */
        NoteEdit: {
            /** Statement */
            statement: string;
        };
        /**
         * Pair
         * @description A live recall pair, with the source it walks to.
         */
        Pair: {
            /** Answer */
            answer: string;
            /** Id */
            id: number;
            /** Placement Id */
            placement_id: number;
            /** Question */
            question: string;
            /** Sessions Correct */
            sessions_correct: number;
            source: components["schemas"]["Source"];
        };
        /**
         * PairWrite
         * @description One entry in a pair set.
         *
         *     An entry with an `id` rewords that pair. An entry with neither `id` nor
         *     `inherit_from` is a new pair at zero. An entry with `inherit_from` is a new
         *     pair taking the lower `sessions_correct` of the pairs it names. A live pair
         *     of the placement absent from the set is retired — see
         *     design/api/API.md#writing-a-pair-set.
         */
        PairWrite: {
            /** Answer */
            answer: string;
            /** Id */
            id?: number | null;
            /** Inherit From */
            inherit_from?: number[];
            /** Question */
            question: string;
        };
        /**
         * PendingPlacement
         * @description A placement waiting on wordsmithing, with everything Claude reads.
         *
         *     See design/flows/Wordsmithing.md#what-claude-reads.
         */
        PendingPlacement: {
            group: components["schemas"]["Group"] | null;
            /** Group Notes */
            group_notes: components["schemas"]["Note"][];
            /** Group Pairs */
            group_pairs: components["schemas"]["Pair"][];
            note: components["schemas"]["Note"];
            /** Pairs */
            pairs: components["schemas"]["Pair"][];
            placement: components["schemas"]["Placement"];
        };
        /**
         * Placement
         * @description A note's residency, as read back.
         */
        Placement: {
            /** Group Id */
            group_id: number | null;
            /** Id */
            id: number;
            /** Note Id */
            note_id: number;
            /** Pairs Stale */
            pairs_stale: boolean;
        };
        /**
         * PlacementMove
         * @description Where a placement is moving to. `None` is the roll.
         */
        PlacementMove: {
            /** Group Id */
            group_id?: number | null;
        };
        /**
         * PlacementRequest
         * @description One residency to create. `group_id` of `None` is the roll.
         */
        PlacementRequest: {
            /** Group Id */
            group_id?: number | null;
            /** Note Id */
            note_id: number;
        };
        /**
         * RollBatch
         * @description `n` due roll pairs. A board without context.
         */
        RollBatch: {
            /** Due */
            due: components["schemas"]["DuePair"][];
        };
        /**
         * Source
         * @description A publication a note was read in.
         */
        Source: {
            /** Author */
            author: string;
            /** Id */
            id: number;
            /** Publication */
            publication?: string | null;
            /** Year */
            year: number;
        };
        /**
         * SourceCreate
         * @description What creating a source asks for. Author and year are required.
         */
        SourceCreate: {
            /** Author */
            author: string;
            /** Publication */
            publication?: string | null;
            /** Year */
            year: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * Verdict
         * @description One pair's grade. The pair is missed unless both boxes are correct.
         */
        Verdict: {
            /** Answer Correct */
            answer_correct: boolean;
            /** Recall Pair Id */
            recall_pair_id: number;
            /** Right Answer */
            right_answer?: string | null;
            /** Right Source */
            right_source?: string | null;
            /** Source Correct */
            source_correct: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    post_confirm_api_confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_draw_api_draw_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DrawSummary"];
                };
            };
        };
    };
    read_boards_api_draw_boards_get: {
        parameters: {
            query?: {
                n?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Board"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_roll_api_draw_roll_get: {
        parameters: {
            query?: {
                n?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RollBatch"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_grade_api_grade_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GradeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GradeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_groups_api_groups_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"][];
                };
            };
        };
    };
    post_group_api_groups_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GroupCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_group_api_groups__group_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_group_api_groups__group_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GroupEdit"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_home_api_home_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Home"];
                };
            };
        };
    };
    read_misses_api_misses_get: {
        parameters: {
            query?: {
                group_id?: number | null;
                placement_id?: number | null;
                since?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Miss"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_notes_api_notes_get: {
        parameters: {
            query?: {
                ungrouped?: boolean;
                roll?: boolean;
                group_id?: number | null;
                source_id?: number | null;
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Note"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_note_api_notes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoteCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Note"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_note_api_notes__note_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                note_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_note_api_notes__note_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                note_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoteEdit"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Note"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_placements_api_placements_get: {
        parameters: {
            query?: {
                pending?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingPlacement"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_placements_api_placements_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlacementRequest"][];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Placement"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_placement_api_placements__placement_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                placement_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlacementMove"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Placement"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_pairs_api_placements__placement_id__pairs_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                placement_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PairWrite"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pair"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_sources_api_sources_get: {
        parameters: {
            query?: {
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Source"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_source_api_sources_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Source"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
