/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/fish/clades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Clades
         * @description Search clades by scientific and common name, optionally at one level.
         */
        get: operations["get_clades_api_fish_clades_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fish/clades/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Clade
         * @description One clade and its ancestors. A `404` is the walk's signal that the clade is new.
         */
        get: operations["get_clade_api_fish_clades__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fish/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Sources
         * @description Search sources by author prefix, year, or a substring of the title.
         */
        get: operations["get_sources_api_fish_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fish/characters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Character
         * @description Enter a character: one transaction writing the clade chain, the source, and both edges.
         *
         *     The response is what the next submission should send, which is how the sticky form stops
         *     creating and starts referring.
         */
        post: operations["post_character_api_fish_characters_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fish/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Image
         * @description Enter an image: the same body as a character, with the file in place of the text.
         *
         *     Any common format is accepted; the server scales it and stores WebP.
         */
        post: operations["post_image_api_fish_images_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fish/images/{img_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Image
         * @description Serve a stored image. This is what a Kin board's image cards point at.
         */
        get: operations["get_image_api_fish_images__img_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kin/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get State
         * @description What the games-list card shows.
         */
        get: operations["get_state_api_kin_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kin/set": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Set
         * @description Generate the day's draw. Idempotent, and it honours carry-over.
         */
        post: operations["post_set_api_kin_set_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kin/board": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Board
         * @description The open board, which is how a board resumes after the app is closed.
         */
        get: operations["get_board_api_kin_board_get"];
        put?: never;
        /**
         * Post Board
         * @description Deal a group. `size` is a maximum; a short group comes back short.
         */
        post: operations["post_board_api_kin_board_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kin/board/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Submit
         * @description Answer the board. Correct slots lock; incorrect ones clear for another try.
         */
        post: operations["post_submit_api_kin_board_submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kin/board/move-on": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Move On
         * @description Give the board up, and return it filled in — so giving up teaches the answer.
         */
        post: operations["post_move_on_api_kin_board_move_on_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Ancestor
         * @description One step of a clade's parent chain.
         */
        Ancestor: {
            /** Name */
            name: string;
            level: components["schemas"]["Level"];
        };
        /**
         * Board
         * @description One round: a group, its cards, and the two palettes.
         *
         *     Every card of every anchor comes down, prefilled where the edge was not drawn — most of a
         *     board is `locked`.
         */
        Board: {
            /** Board Id */
            board_id: number;
            /** Level */
            level: string;
            /** Ended */
            ended: boolean;
            /** Scored */
            scored: boolean;
            /** Clades */
            clades: components["schemas"]["PaletteClade"][];
            /** Citations */
            citations: components["schemas"]["Citation"][];
            /** Cards */
            cards: components["schemas"]["Card"][];
            /** Labels */
            labels: {
                [key: string]: string;
            };
        };
        /** Body_post_image_api_fish_images_post */
        Body_post_image_api_fish_images_post: {
            /** Json */
            json: string;
            /** Image */
            image: string;
        };
        /**
         * Card
         * @description One image or one character, with a clade slot above it and a source slot below.
         */
        Card: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "image" | "character";
            /** Img Id */
            img_id?: string | null;
            /** Text */
            text?: string | null;
            clade: components["schemas"]["Slot"];
            src: components["schemas"]["Slot"];
        };
        /**
         * CharacterCreated
         * @description What the next submission should send, which is how the sticky form stops creating.
         */
        CharacterCreated: {
            /** Clade */
            clade: string;
            /** Source */
            source: number;
            /** Char Id */
            char_id: number;
        };
        /**
         * CharacterEntry
         * @description One character, its clade and its source.
         *
         *     `clade` and `source` are a reference-or-object union: a bare name or id means *reuse*, an
         *     object means *create*. The client already did the lookups, so it says which it meant.
         */
        CharacterEntry: {
            /** Clade */
            clade: string | components["schemas"]["NewClade"];
            /** Source */
            source: number | components["schemas"]["NewSource"];
            /** Text */
            text: string;
        };
        /**
         * Citation
         * @description A chip in the citation pool, holding only the sources behind due `src` slots.
         */
        Citation: {
            /** Src */
            src: number;
            /** Label */
            label: string;
        };
        /**
         * CladeDetail
         * @description One clade and its ancestors, narrowest to broadest.
         *
         *     This is what the entry form's walk reads: a `404` instead means the clade is new.
         */
        CladeDetail: {
            /** Name */
            name: string;
            /** Common Name */
            common_name: string | null;
            level: components["schemas"]["Level"];
            /** Ancestors */
            ancestors: components["schemas"]["Ancestor"][];
        };
        /**
         * CladeResult
         * @description A clade as a search result.
         */
        CladeResult: {
            /** Name */
            name: string;
            /** Common Name */
            common_name: string | null;
            level: components["schemas"]["Level"];
        };
        /**
         * DealRequest
         * @description `size` is a maximum. A short group comes back short.
         */
        DealRequest: {
            /** Size */
            size: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ImageCreated
         * @description What the next submission should send, which is how the sticky form stops creating.
         */
        ImageCreated: {
            /** Clade */
            clade: string;
            /** Source */
            source: number;
            /** Img Id */
            img_id: string;
        };
        /**
         * KinState
         * @description What the games-list card shows.
         *
         *     `generated_on` is null when no set exists. Together with `anchors_left` it is everything the
         *     card needs: a spent set drawn today reads *done for today*, the same set read tomorrow reads
         *     *not generated*.
         */
        KinState: {
            /** Generated On */
            generated_on: string | null;
            /** Anchors Total */
            anchors_total: number;
            /** Anchors Left */
            anchors_left: number;
            /** Open Board */
            open_board: boolean;
        };
        /**
         * Level
         * @description How broad a clade is, from broadest to narrowest.
         *
         *     Adding a member is a schema change, deliberately: the set stays small or the games get vague.
         * @enum {string}
         */
        Level: "class" | "order" | "suborder" | "family" | "subfamily" | "genus" | "species";
        /**
         * NewAncestor
         * @description A clade the walk found missing, to be created with the entry.
         */
        NewAncestor: {
            /** Name */
            name: string;
            level: components["schemas"]["Level"];
        };
        /**
         * NewClade
         * @description A clade to create, with the chain of ancestors that must be created above it.
         *
         *     `new_ancestors` runs narrowest to broadest and `parent` names the existing clade the top of
         *     it hangs from. A `parent` of null makes the top of the chain a root.
         */
        NewClade: {
            /** Name */
            name: string;
            /** Common Name */
            common_name?: string | null;
            level: components["schemas"]["Level"];
            /** New Ancestors */
            new_ancestors?: components["schemas"]["NewAncestor"][];
            /** Parent */
            parent?: string | null;
        };
        /**
         * NewSource
         * @description A source to create. Its `src` is assigned by the database.
         */
        NewSource: {
            /** Author */
            author: string;
            /** Year */
            year: number;
            /** Title */
            title: string;
        };
        /**
         * PaletteClade
         * @description A chip in the clade palette: the group's anchors, and nothing else.
         */
        PaletteClade: {
            /** Name */
            name: string;
            /** Common Name */
            common_name: string | null;
        };
        /**
         * Slot
         * @description One blank on a card.
         *
         *     `due` is blank and the player fills it; `locked` is shown filled and is not editable.
         *     `value` is a clade name on a clade slot and a `src` on a source slot, and is null while the
         *     slot is live — the right answer is never returned to a board still being played.
         */
        Slot: {
            /** Slot */
            slot: string;
            /**
             * State
             * @enum {string}
             */
            state: "due" | "locked";
            /** Value */
            value: string | number | null;
        };
        /**
         * SourceResult
         * @description A source as a search result, carrying the citation a chip displays.
         */
        SourceResult: {
            /** Src */
            src: number;
            /** Author */
            author: string;
            /** Year */
            year: number;
            /** Title */
            title: string;
            /** Label */
            label: string;
        };
        /**
         * SubmitRequest
         * @description Every due slot at once — a slot only becomes an answer at submission.
         */
        SubmitRequest: {
            /** Slots */
            slots: {
                [key: string]: string | number;
            };
        };
        /**
         * SubmitResponse
         * @description What one submission did.
         *
         *     `scored` is true only on the first submission, the one that moves
         *     `sessions_since_last_failed`. `complete` true means every slot is locked and the board is
         *     finished.
         */
        SubmitResponse: {
            /** Results */
            results: {
                [key: string]: "correct" | "wrong";
            };
            /** Complete */
            complete: boolean;
            /** Scored */
            scored: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_clades_api_fish_clades_get: {
        parameters: {
            query?: {
                q?: string;
                level?: components["schemas"]["Level"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CladeResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_clade_api_fish_clades__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CladeDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sources_api_fish_sources_get: {
        parameters: {
            query?: {
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_character_api_fish_characters_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CharacterEntry"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_image_api_fish_images_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_post_image_api_fish_images_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_image_api_fish_images__img_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                img_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_state_api_kin_state_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KinState"];
                };
            };
        };
    };
    post_set_api_kin_set_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KinState"];
                };
            };
        };
    };
    get_board_api_kin_board_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Board"];
                };
            };
        };
    };
    post_board_api_kin_board_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DealRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Board"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_submit_api_kin_board_submit_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmitResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_move_on_api_kin_board_move_on_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Board"];
                };
            };
        };
    };
}
